# Automatically generated by hassfest.
# To update, run python3 -m script.hassfest -p docker
ARG BUILD_FROM
FROM ${BUILD_FROM}

# Synchronize with homeassistant/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME=240000 \
    UV_SYSTEM_PYTHON=true

ARG QEMU_CPU

# Install uv
RUN pip3 install uv==0.2.27

WORKDIR /usr/src

# Install system dependencies
RUN apt-get update && \
    apt-get install -y build-essential python3-dev libpcap-dev

## Setup Home Assistant Core dependencies
COPY requirements.txt homeassistant/
COPY homeassistant/package_constraints.txt homeassistant/homeassistant/
RUN \
    uv pip install \
        -r homeassistant/requirements.txt

COPY requirements_all.txt home_assistant_frontend-* home_assistant_intents-* homeassistant/
RUN uv pip install setuptools # Install setuptools first

# Install additional dependencies
RUN \
    uv pip install \
        -r homeassistant/requirements_all.txt

## Setup Home Assistant Core
COPY . homeassistant/
RUN \
    uv pip install \
        -e ./homeassistant \
    && python3 -m compileall \
        homeassistant/homeassistant

# Install additional Python packages
RUN pip3 install mysqlclient numpy

# Home Assistant S6-Overlay
COPY rootfs /

WORKDIR /config

CMD ["/usr/local/bin/python", "-m", "homeassistant", "--config", "/config"]